# Generated by Django 5.1.7 on 2025-03-22 19:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Diffusion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("finished", "Finished"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("number_of_iterations", models.PositiveIntegerField()),
                ("integration", models.CharField(max_length=36)),
                (
                    "sources",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=12), size=None
                    ),
                ),
                (
                    "destinations",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=12), size=None
                    ),
                ),
                (
                    "shock_types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=12), size=None
                    ),
                ),
                (
                    "shock_amounts",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=12), size=None
                    ),
                ),
                ("threshold_one", models.IntegerField()),
                ("threshold_two", models.IntegerField()),
                ("threshold_three", models.IntegerField()),
            ],
        ),
    ]
