# Generated by Django 5.1.7 on 2025-03-22 20:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diffusion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="diffusion",
            name="identifier",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="diffusion",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
