# Generated by Django 5.1.7 on 2025-03-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diffusion", "0002_diffusion_identifier_alter_diffusion_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diffusion",
            name="threshold_one",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="diffusion",
            name="threshold_three",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="diffusion",
            name="threshold_two",
            field=models.FloatField(),
        ),
    ]
