# Generated by Django 5.1.7 on 2025-03-22 20:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diffusion", "0003_alter_diffusion_threshold_one_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diffusion",
            name="destinations",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=12, null=True),
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="diffusion",
            name="shock_amounts",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=12, null=True),
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="diffusion",
            name="shock_types",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=12, null=True),
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="diffusion",
            name="sources",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=12, null=True),
                size=None,
            ),
        ),
    ]
