# Generated by Django 5.1.7 on 2025-03-24 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diffusion", "0004_alter_diffusion_destinations_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diffusion",
            name="identifier",
        ),
    ]
