# Generated by Django 5.1.7 on 2025-03-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diffusion", "0005_remove_diffusion_identifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="diffusion",
            name="logs",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
