# Generated by Django 5.1.7 on 2025-03-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diffusion", "0006_diffusion_logs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diffusion",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("finished", "Finished"),
                    ("failed", "Failed"),
                    ("deleted", "Deleted"),
                ],
                default="pending",
                max_length=12,
            ),
        ),
    ]
