# Generated by Django 5.1.7 on 2025-03-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diffusion", "0007_alter_diffusion_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="diffusion",
            name="name",
            field=models.CharField(blank=True, max_length=72, null=True),
        ),
    ]
