# Generated by Django 5.1.7 on 2025-06-08 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataset", "0001_initial"),
        ("diffusion", "0008_diffusion_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diffusion",
            name="integration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dataset.dataset"
            ),
        ),
    ]
